networks:
  edge:

services:
  genomain-open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
        VITE_GENOMAIN_API_URL: ${VITE_GENOMAIN_API_URL}
        VITE_MS_GRAPH_SCOPES: ${VITE_MS_GRAPH_SCOPES}
        VITE_MS_CLIENT_ID: ${VITE_MS_CLIENT_ID}
      dockerfile: Dockerfile
    image: genomain-open-webui:local
    container_name: genomain-open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      WEBUI_SECRET_KEY: ${WEBUI_JWT_SECRET_KEY}
      WEBUI_JWT_SECRET_KEY: ${WEBUI_JWT_SECRET_KEY}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    restart: unless-stopped
    networks: [edge]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run genomain-openwebui-tunnel
    depends_on:
      - genomain-open-webui
    volumes:
      - /Users/geno/.cloudflared:/etc/cloudflared
    networks: [edge]

volumes:
  open-webui:
#docker compose -f docker-compose.genomain.yaml --env-file .env.staging up --build
